version: "3.9"
services:
    app:
        container_name: snake_game
        image: snake-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "5002:80" 
